version: '3.8'

services:
  beach-box-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3003:3003"
    volumes:
      - .:/app
    working_dir: /app/apps/beach-box-landing
    command: pnpm dev